---
title: ''
format: pdf
bibliography: ../references.bib
---

# Zusammenfassung (German abstract) {.unnumbered}

Die maximale Sauerstoffaufnahme (V̇O~2max~) ist die wichtigste physiologische Kenngröße der Ausdauerleistungsfähigkeit. Zur Bestimmung der V̇O~2max~ werden während eines Rampentests die Atemgase kontinuierlich gemessen. Die üblicherweise im breath-by-breath-Verfahren erhobenen Daten erfordern eine Weiterverarbeitung um die V̇O~2max~ zu bestimmen. Unterschiedliche Verfahren der Datenverarbeitung können die gemessenen V̇O~2max~ beeinflussen. Ziel der vorliegenden Arbeit ist es, anhand eines scoping review zu bestimmen, welche Datenverarbeitungsstrategien in der wissenschaftlichen Literatur genutzt werden, um diese im Anschluss anhand experimenteller Daten zu vergleichen. Für den Review wurde eine Zufallsstichprobe von 500 Artikeln untersucht; der experimentelle Vergleich erfolgte anhand von 72 standardisierten Rampentests auf dem Laufband. Die im Review untersuchten Studien benutzen eine Vielzahl von verschiedenen Datenverabeitungsstrategien, welche häufig nur unzureichend beschrieben werden. Die unterschiedlichen Strategien können die V̇O~2max~ im Median zu mehr als 5% beeinflussen, mit deutlich höheren individuellen Abweichungen. Die Ergebnisse verdeutlichen den Bedarf einer Standardisierung und korrekter Darstellung der benutzten Datenverarbeitungsstrategien zur Bestimmung der V̇O~2max~. Diese Arbeit bietet hierfür Empfehlungen zur Verwendung und Vergleichbarkeit verschiedener Strategien, sowie Richtlinien zur Beschreibung dieser im Rahmen wissenschaftlicher Studien.
