---
title: ''
format: pdf
bibliography: ../references.bib
---

# Conclusion

The determination of V̇O~2max~ from raw breath-by-breath data requires some form of data post-processing. As shown by the scoping review, researchers use a variety of strategies for this data processing. I demonstrated on experimental data, that different processing strategies systematically bias the V̇O~2max~ assessment, which can ultimately lead to misclassification of individuals or groups and incorrect evaluation of interventions. Despite contradictory recommendations, binned time average remain by far the most common data processing strategy. The calculation intervals for time averages range from 5 to 60 seconds in the reviewed literature, which heavily influences the V̇O~2max~ value obtained. Almost all research did only incompletely report on their data processing to determine V̇O~2max~, and as such can be regarded non-reproducible. To ensure valid and reproducible V̇O~2max~ assessments, researchers should at minimum report their processing strategy based on a set of guidelines I developed in this thesis. Despite calls for standardization of data processing, to date no evidence for an optimal strategy exists, but digital filtering (e.g., zero-phase Butterworth filter) appears to generate a more reasonable data smoothing compared to traditional (moving) averages. I encourage researchers to share their raw gas exchange data and use programming software for data analysis, to minimize the bias due to data processing when determining the V̇O~2max~.
