---
title: ''
format: pdf
bibliography: ../references.bib
---

# Discussion

The collected data shows, that current research uses a variety of strategies to determine V̇O~2max~, which directly influences the values obtained. Many articles only incompletely report on their methods and use outdated strategies. These practices hinder the validity and reproducibility of V̇O~2max~ measurement.

## Current state of data processing

Despite calls to use moving averages [@robergs2003; @robergs2010], binned time averages remain the most commonly used data processing strategy to determine V̇O~2max~ in the reviewed literature (see @fig-strategies). These numbers are generally in line with the findings of the non-systematic search by @midgley2007 and the survey by @robergs2010. It is somewhat surprising, that practices have not changes in recent years despite the publication of recommendations, that highly discourage researchers from using binned averages [@robergs2010]. Using binned time averages leads to systematically lower V̇O~2max~ values as compared to moving averages (see @fig-comparison). The peak in oxygen uptake may fall in between two average intervals, resulting in an underestimation of V̇O~2max~ (see @fig-example for an example). Binned time average revoke the most important argument for measuring breath-by-breath: the high temporal resolution of data. Despite these arguments speaking against the use of binned time averages, my review demonstrates that they remain very common in scientific literature.

Breath-based averages seem to be more common (≈ 8%) than reported previously (\< 1%) [@midgley2007], but less common than assessed in self-reporting (≈ 17%) [@robergs2010]. The increasing proportion of breath-based averages may be explained by publications in the recent years advocating for them [@robergs2003; @robergs2010]. However the proportion of breath-based averages is much smaller than that of binned time averages, which have not been recommended in such a way.

The length of the calculation intervals is highly diverse within the literature (see @fig-duration). This may reflect contradictory recommendation [@howley1995; @robergs2003]. As long as there is no consensus on the arguments speaking for shorter or longer calculation intervals, there appears to be no optimal interval duration. As different interval duration can heavily influence V̇O~2max~ by more than 5% on a median level (see @fig-comparison), the exact reporting of the data processing strategy remains essential for interpretation.

The exact reasons for exercise scientist ignoring most recommendations by using binned time averages remain unknown. Some researchers may simply not be aware of the impact different data processing strategies have on the V̇O~2max~, but past publications on this issues have been widely cited [@robergs2010; @midgley2007; @astorino2009] and should be known to most scientists in this field. Researchers may also use binned averages for traditional reasons. Douglas bags, as well as many mixing chamber devices, measure the oxygen uptake over fixed time intervals, producing data appearently similar to those by a binned time average of breath-by-breath data. But comparability with older data should only be an issue when using data acquired by different measurement methods within on analysis. Current studies using new breath-by-breath data do not reasonably need to rely on outdated methods of data processing.

A major source for choosing suboptimal processing strategies may be limitations by analysis software. My review shows that most researchers use the software of the metabolic cart's manufacturer to analyse the gas exchange data. These software may by default output binned time averages instead of raw breath-by-breath data. Moreover, further processing (e.g., interpolation, moving averages) may require the use of additional software. This is also an reasonable explanation why digital filtering has --- despite recommended by @robergs2010 --- not been used in a single study reviewed here: standard distributions of common data analysis software (e.g., Microsoft Excel) lack the capability to perform such operations. The common malpractices of data processing are likely to be both attributed to a lack of awareness and a lack of easy-to-use software solutions.

## Impact of different data processing

The different data processing strategies found in the literature directly bias the V̇O~2max~ determination (see @fig-comparison), and as such can influence the classification of individuals, evaluation of training success, and assessment of V̇O~2max~ attainment. In accordance with previous findings [@johnson1998; @astorino2009; @sell2021] --- and pure logic --- longer calculation intervals lead to lower V̇O~2max~ values (see @fig-comparison). The analysed data shows median differences up to 5-7% between processing strategies, which is in accordance with previous research. Some studies reported even higher mean differences up to 20% [@myers1990], but only when including raw breath-by-breath data in the comparison. The evaluation of unprocessed raw data for its maximum is highly erroneous (see the individual breath data points in @fig-example) and as such not performed in research (see @fig-duration); so there is no reason to include it in a comparison to other strategies. While previous research was often conducted in sedentary or recreational individuals, this thesis now presents evidence, that a similar effect of data processing strategies on V̇O~2max~ exists in well-trained athletes.

Binned time averages lead to systematically lower V̇O~2max~ values compared with moving averages, for the reasons explained above. While this general trend has been acknowledged previously [@martin-rincon2019], it has not been quantified. The data presented in this thesis suggest a ≈-1% lower median V̇O~2max~ when using binned averages compared with moving averages of the same calculation interval length. This difference is well within the measurement error of most if not all metabolic carts, but is systematic and as such may bias the evaluation in scenarios where small changes in V̇O~2max~ are important (e.g. in elite sports).

Moving time and moving breath averages lead to almost identical V̇O~2max~ values on a median level (@fig-comparison). This is hardly surprising, as the athletes in this study reached respiratory rates around 60 min^-1^ (see @fig-rr), resulting in equivalent time- and breath-based interval lengths. For an athletic population, V̇O~2max~ values obtained by moving time and moving breath average can approximately used interchangeable. Given that less trained individual will likely display lower respiratory rates during exercise tests to exhaustion [@blackie1991], this finding will not translate to a sedentary population.

The exact impact of data processing strategies on the V̇O~2max~ is highly individual. Most research did present only comparisons of mean values, with results in accordance with those found here [@martin-rincon2019]. On an individual level, data processing strategies may impact the V̇O~2max~ in different severity. For example, for 10% of the investigated athletes a binned time average of 5 seconds lead to a V̇O~2max~ \<3% higher than by a 30 second average, while for another 10% the V̇O~2max~ was \>6% higher (see @fig-comparison). Current values reported and equation derived compare strategies on a group level [@martin-rincon2019], which improves comparability of group results for meta-analyses or group classification. However on a individual level such work does not help. Changes in the impact of different data processing strategies on V̇O~2max~ range from 1-2% in some to more than 10% in other individuals. Hence when evaluating V̇O~2max~ data from different tests in a single individual obtained by using different processing methods, there is no way to accurately compare these values even when the processing strategies are reported. While the comparison of V̇O~2max~ from different processing strategies require their reporting for an sufficient analysis on a group level, on the individual level the raw data from each test is required.

## Guidelines for data processing and reporting

This thesis focussed on the occurrence and impact of different data processing strategies, but did not investigate their validity in the first place. However the results of the scoping review and experimental comparison allow to specify existing recommendation for data processing and set new guidelines for data reporting.

I highly disregard researchers from continuing to use binned time averages to determine V̇O~2max~. The main reason for such procedure is pure tradition, as it reduces the breath-by-breath data in an inappropriate way leading to a small, yet systematic, underestimation of V̇O~2max~. Moving time or moving breath averages are preferable to binned averages. In a athletic population they may be used equivalent, but in sedentary individuals breath-based averages will likely lead to lower V̇O~2max~ values than time-based averages with the same interval length parameter. While using a constant breath interval will lead to a similar degree of data smoothing regardless of the training status, using a constant time interval will lead to the same physiological time-frame for determining V̇O~2max~ (but with a different degree of data smoothing). From a data processing perspective, I prefer using breath-based moving averages, while keeping in mind, that this may underestimate true V̇O~2max~ in individuals with a low respiratory rate in the end of the exercise test.

Digital filtering seems to be a promising method, as it markedly reduces the variability moving averages have due to single data outliers (see @fig-example). I therefore agree with @robergs2010, who recommends digital filters over any classical averaging procedure. The exact type of filter and values of filter parameters to be used have not yet been systematically investigated, and it is unclear whether it is possible at all to determine criteria for identifying an optimal filter. However, a Butterworth filter, as proposed by @robergs2010, seems to produce reasonably smoothed data. Note, that a single Butterworth filter comprises a time lag, a fact highlighted by @weir2004 that was not acknowledged by @robergs2010. To allow for a correct phasing of data, as well as for a correct V̇O~2max~ determination when the measurement is shortly terminated after reaching exhaustion, a zero-phase filter is needed. A zero-phase forward-backward Butterworth filter (as suggested by @weir2004) seems to produce reasonable smoothing when used with the parameters suggested by @robergs2010 (low-pass cut-off frequency: 0.04 Hz; third order; see @fig-example). It should be noted, that despite using the same parameters the degree of filtering varies from that by @robergs2010, as the filter is applied twice, changing the overall magnitude of parameters. Other filtering parameters may be as reasonable as this, but it is unclear how to objectively compare them.

I recommend to use a zero-phase forward-backward Butterworth filter on the raw breath-by-breath data. The V̇O~2max~ is then defined as the highest single filtered data point. An filter order of 3 and a low cut-off frequency of 0.04 Hz appear to be reasonable parameters for each filter. While such data processing has advantages over traditional data processing forms, it requires specialized software.

To compare and evaluate V̇O~2max~ values from different studies, knowledge of the underlying data processing strategy is crucial. The review presented here shows that almost half of the studies that measured V̇O~2max~ did not describe their processing strategy. Other aspects of the data processing, such as outlier filtering or rationale for the chosen procedure were only in rare instances reported (see @tbl-reporting). @tbl-recommendation lists 7 item that should be reported to provide sufficient information on the data processing strategy used to determine V̇O~2max~. These items may be reported in form of a check-list, as an in-text enumeration or in sentence form. An example paragraph containing all the relevant information for the current study would be:

> *"We measured breath-by-breath data during the ramp tests with a ZAN 600 device (nSpire Health, Inc., Longmont, CO, United States of America). The raw data was analyzed without any previous filtering by using a low-pass forward-backward Butterworth filter (each filter: 3rd order, 0.04 Hz cut-off) implemented in the spiro Package for R [@nolte2022]. This strategy produces similar results as that recommended by @robergs2010, but does not produce a time lag."*

| reporting item        | description                                                                                                           |
|-----------------------|-----------------------------------------------------------------------------------------------------------------------|
| Metabolic Cart        | State the exact device model and manufacturer                                                                         |
| Measurement Mode      | State the measurement mode (e.g., mixing chamber, breath-by-breath,...)                                               |
| Software              | State the name and version of the software used for data analysis                                                     |
| Preprocessing         | State if and how data underwent any initial modification (e.g., filtering of outliers, interpolation) before analysis |
| Processing Strategy   | State the exact data processing strategy used to determine the V̇O~2max~ (e.g., binned time averages)                  |
| Processing Parameters | State the parameters used for the processing strategy (e.g., length of averaging interval)                            |
| Rationale             | State the rationale for using the processing strategy (e.g., reference to recommendations)                            |

: Recommendations for reporting data processing strategies to determine V̇O~2max~. {#tbl-recommendation}

Note that the correct reporting of an exercise test to determine V̇O~2max~ requires more information than those on data processing. Further aspects to be reported include, but are not limited to, the study population, the exercise protocol, the device calibration, and criteria to stop the test. In cases where journals endorse word limits on articles, these reporting --- including the reporting on data processing strategies --- may be included in supplementary files. The correct and detailed reporting of data processing strategies, as well as other test characteristics, is crucial for interpreting presented V̇O~2max~ values.

The results of this thesis suggest that comprehensive reporting facilitates approximate comparisons of V̇O~2max~ data on a group level derived using different data processing strategies. But on an individual level and for a precise comparison, reporting is not enough, as differences between data processing strategies may vary between individuals and are potentially influenced by training status. Sharing of the raw metabolic exchange data is the solution to this problem. It allows any researcher to recalculate the V̇O~2max~ using their preferred data processing strategy. Anonymization of raw gas exchange data files should not be a big deal for researchers, since most of these files are structured in a simple way and allow to easily remove any personal information (if this has not been done in the metabolic cart's system before). In terms of reproducibility of V̇O~2max~ determination, an even superior way to correct reporting and raw data sharing is to additionally share data analysis code. This allows any researcher to independently reproduce the V̇O~2max~ processing conducted within a study, but requires the data analysis to take place in a programming, or at least code generating, environment. Luckily such programs for the purpose of analyzing gas exchange data exist as free open-source software [@maturana2022; @nolte2022].

## Limitations

Due to the sheer quantity of the publications investigating V̇O~2max~, it was not possible to perform an exhaustive review of the literature. The scoping review therefore relies on a random sample which not necessarily exactly captures trends of the whole literature. However, efforts were made --- such as random sampling and systematic article exclusions --- to ensure the sample to be representative. Notable, almost half of the studies did not report their data processing strategy at all. The data processing strategies used in the literature could only be described when studies reported them.

Ambiguities in the reporting of the investigated studies may impact the analysis results. For example some studies using long binned averages (e.g. 60 seconds) may have in fact been using multiple binned averages of shorter durations (e.g., 4x15 second), without describing this correctly. Moreover the exact definitions for building binned averages varied within the literature: While most studies defined the binning periods from the beginning of the exercise, some may have defined them from the endpoint. Additionally some studies reviewed did not define the maximum, but a predefined binned average period as their V̇O~2max~ (for example the last bin, regardless of its value). In situations where the maximum in oxygen uptake is reached considerably before exhaustion (i.e., a long plateau in oxygen uptake exists) this may lead to different results than a traditional binned average. I did not seperately consider such sub-categories of data processing strategies, as they may not be very common and are often hard to precisely investigate due to ambiguity in reporting.

The experimental comparison of different data processing strategies was conducted on a standardized data set of exercise tests. This standardization in terms of training status, exercise protocol, and measurement device helps to highlight the impact of different data processing even in a relatively homogeneous data set. However the results may only partly be transferable to different settings, such as individuals with less training background. I did not conduct an formal analysis of the validity or reliability of different data processing strategies, so recommendations regarding their use rely on theoretical derivations and prior research. Since the reliability of different strategies appears to be similar [@midgley2007; @martin-rincon2019] and currently no accepted methods to quantify validity of V̇O~2max~ exist, the presented approach is sufficient to derive recommendations for data processing strategies to determine V̇O~2max~.
